---
title: "kaggle_eda"
author: "Hyeonho Lee"
date: "2018년 9월 19일"
output: html_document
---


```{r}
library(data.table)
library(jsonlite)
library(readr)
library(dplyr)
library(tidyr)
library(magrittr)
library(lubridate)
library(purrr)
library(ggplot2)
library(gridExtra)
library(countrycode)
library(highcharter)
```

```{r}
setwd("D:/kaggle_compitition/all")
dtrain = read_csv("train.csv", n_max = 10000)
```


```{r}
glimpse(dtrain)
```

```{r}
# convert date column from character to Date class
dtrain$date <- as.Date(as.character(dtrain$date), format='%Y%m%d')
```


```{r}
tr_device <- paste("[", paste(dtrain$device, collapse = ","), "]") %>% fromJSON(flatten = T)
tr_geoNetwork <- paste("[", paste(dtrain$geoNetwork, collapse = ","), "]") %>% fromJSON(flatten = T)
tr_totals <- paste("[", paste(dtrain$totals, collapse = ","), "]") %>% fromJSON(flatten = T)
tr_trafficSource <- paste("[", paste(dtrain$trafficSource, collapse = ","), "]") %>% fromJSON(flatten = T)
```

```{r}
dtrain <- cbind(dtrain, tr_device, tr_geoNetwork, tr_totals, tr_trafficSource) %>%
  as.data.table()

# drop the old json columns
dtrain[, c('device', 'geoNetwork', 'totals', 'trafficSource') := NULL]
```


```{r}
# get number of unique values in each column
unique <- sapply(dtrain, function(x) { length(unique(x)) })

# subset to ==1
one_val <- names(unique[unique == 1])

# drop columns from dtrain
dtrain[, (one_val) := NULL]
```


```{r}
glimpse(dtrain)
```



```{r}
# character columns to convert to numeric
num_cols <- c('hits', 'pageviews', 'bounces', 'newVisits',
              'transactionRevenue')

# change columns to numeric
dtrain[, (num_cols) := lapply(.SD, as.numeric), .SDcols=num_cols]
```



```{r}
#Divide transactionRevenue by 1,000,000
dtrain[, transactionRevenue := transactionRevenue / 1e+06]
```

```{r}
# values to convert to NA
na_vals <- c('unknown.unknown', '(not set)', 'not available in demo dataset')

for(col in names(dtrain)) {
  
  set(dtrain, i=which(dtrain[[col]] %in% na_vals), j=col, value=NA)
  
}
```

Missing Value
```{r}
data.table(
  pmiss = sapply(dtrain, function(x) { (sum(is.na(x)) / length(x)) }),
  column = names(dtrain)
  ) %>%
ggplot(aes(x = reorder(column, -pmiss), y = pmiss)) +
geom_bar(stat = 'identity', fill = 'steelblue') + 
  scale_y_continuous(labels = scales::percent) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    title='Missing data by feature',
    x='Feature',
    y='% missing')
```


Data Exploration
```{r}
time_range <- range(dtrain$date)
print(time_range)
```


Target Variable (transaction revenue)
```{r}
rev_range <- round(range(dtrain$transactionRevenue, na.rm=TRUE), 2)
print(rev_range)
```

```{r}
dtrain %>% 
  ggplot(aes(x=log(transactionRevenue), y=..density..)) + 
  geom_histogram(fill='steelblue', na.rm=TRUE, bins=40) + 
  geom_density(aes(x=log(transactionRevenue)), fill='orange', color='orange', alpha=0.3, na.rm=TRUE) + 
  labs(
    title = 'Distribution of transaction revenue',
    x = 'Natural log of transaction revenue'
  )
```


```{r}
g1 <- dtrain[, .(n = .N), by=date] %>%
  ggplot(aes(x=date, y=n)) + 
  geom_line(color='steelblue') +
  geom_smooth(color='orange') + 
  labs(
    x='',
    y='Visits (000s)',
    title='Daily visits'
  )

g2 <- dtrain[, .(revenue = sum(transactionRevenue, na.rm=TRUE)), by=date] %>%
  ggplot(aes(x=date, y=revenue)) + 
  geom_line(color='steelblue') +
  geom_smooth(color='orange') + 
  labs(
    x='',
    y='Revenue (unit dollars)',
    title='Daily transaction revenue'
  )

grid.arrange(g1, g2, nrow=2)
```

```{r}
dtrain[, .(revenue = sum(transactionRevenue, na.rm=TRUE)), by=channelGrouping] %>%
  ggplot(aes(x=reorder(channelGrouping, -revenue), y=revenue)) + 
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Channel Grouping', 
       y='Revenue (unit dollars)',
       title='Distribution of revenue by channel grouping')
```



Device Features
```{r}
g1 <- dtrain[, .(n=.N/1000), by=operatingSystem][
  n > 0.001
] %>%
  ggplot(aes(x=reorder(operatingSystem, -n), y=n)) + 
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Operating System', 
       y='# of visits in data set (000s)',
       title='Distribution of visits by device operating system') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

g2 <- dtrain[, .(revenue = sum(transactionRevenue, na.rm=TRUE)), by=operatingSystem][
  revenue > 0, 
] %>%
  ggplot(aes(x=reorder(operatingSystem, -revenue), y=revenue)) +
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Operating System',
       y='Revenue (unit dollars)',
       title='Distribution of revenue by device operating system') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

grid.arrange(g1, g2, nrow=2)
```


```{r}
g1 <- dtrain[, .(n=.N/1000), by=browser][
  1:10
] %>%
  ggplot(aes(x=reorder(browser, -n), y=n)) + 
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Browser', 
       y='# of visits in data set (000s)',
       title='Distribution of visits by browser (Top 10 browsers)') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

g2 <- dtrain[, .(revenue = sum(transactionRevenue, na.rm=TRUE)/1000), by=browser][
  1:10
] %>%
  ggplot(aes(x=reorder(browser, -revenue), y=revenue)) +
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Browser',
       y='Revenue (dollars, 000s)',
       title='Distribution of revenue by browser (top 10 browsers)') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

grid.arrange(g1, g2, nrow=2)
```

```{r}
g1 <- dtrain[, .(n=.N/1000), by=deviceCategory]%>%
  ggplot(aes(x=reorder(deviceCategory, -n), y=n)) + 
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Device Category', 
       y='# of records in data set (000s)',
       title='Distribution of records by device category') + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

g2 <- dtrain[, .(revenue = sum(transactionRevenue, na.rm=TRUE)/1000), by=deviceCategory] %>%
  ggplot(aes(x=reorder(deviceCategory, -revenue), y=revenue)) +
  geom_bar(stat='identity', fill='steelblue') +
  labs(x='Device category',
       y='Revenue (dollars, 000s)',
       title='Distribution of revenue by device category') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

grid.arrange(g1, g2, ncol=2)
```




```{r}
dtrain %>%
  ggplot(aes(x=log(transactionRevenue), y=..density.., fill=isMobile)) +
  geom_density(alpha=0.5) + 
  scale_fill_manual(values = c('steelblue', 'orange')) + 
  labs(title='Distribution of log revenue by mobile and non-mobile devices')
```


Geographic Features
```{r}
dtrain[, .(revenue = sum(transactionRevenue, na.rm=TRUE)/1000), by = continent] %>%
  ggplot(aes(x=reorder(continent, revenue), y=revenue)) + 
  geom_bar(stat='identity', fill='steelblue') + 
  coord_flip() + 
  labs(x='', y='Revenue (dollars, 000s)', title='Total transaction revenue by continent')
```

```{r}
# group by country and calculate total transaction revenue (log)
by_country <- dtrain[, .(n = .N, revenue = log(sum(transactionRevenue, na.rm=TRUE))), by = country]
by_country$iso3 <- countrycode(by_country$country, origin='country.name', destination='iso3c')
by_country[, rev_per_visit := revenue / n]

# create the highcharter map of revenue by country
highchart() %>%
    hc_add_series_map(worldgeojson, by_country, value = 'revenue', joinBy = 'iso3') %>%
    hc_title(text = 'Total transaction revenue by country (natural log)') %>%
    hc_subtitle(text = "August 2016 to August 2017") %>%
    hc_tooltip(useHTML = TRUE, headerFormat = "",
        pointFormat = "{point.country}: ${point.revenue:.0f}")
```



```{r}
# function to map transaction revenue by continent
map_by_continent <- function(continent, map_path) {
  
  mdata <- dtrain[
    continent == continent, .(n = .N, revenue = log(sum(transactionRevenue, na.rm=TRUE))), by=country]
  
  mdata$iso3 <- countrycode(mdata$country, origin='country.name', destination='iso3c')
  
  hcmap(map=map_path, data=mdata, value='revenue', joinBy=c('iso-a3', 'iso3')) %>%
  hc_title(text = 'Total transaction revenue by country (natural log of unit dollars)') %>%
  hc_subtitle(text = "August 2016 to August 2017") %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "",
      pointFormat = "{point.country}: {point.revenue:.0f}")
}

# call function for Europe
map_by_continent(continent='Europe', map_path='custom/europe')
```


```{r}
map_by_continent('Africa', 'custom/africa')
```


```{r}
map_by_continent('Asia', 'custom/asia')
```


```{r}
map_by_continent('Americas', 'custom/south-america')
```

```{r}
map_by_continent('Americas', 'custom/north-america')
```

```{r}
map_by_continent('Oceania', 'custom/oceania')
```

```{r}
map_by_continent('Antarctica', 'custom/antarctica')
```


Totals Features
```{r}
dtrain[pageviews <= 100, ] %>% 
  ggplot(aes(x=pageviews, y=..density..)) + 
  geom_histogram(fill='steelblue') + 
  labs(title='Pageviews per visit')
```

```{r}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```


Traffic Source Features
```{r}
# split networkDomain column on '.', add to dtrain
dtrain[, domain := tstrsplit(dtrain$networkDomain, '\\.', keep=c(2))][
    # add the '.' back in
  , domain := paste0('.', domain)
]

g1 <- dtrain[!is.na(networkDomain), .(n = .N), by = domain][order(-n)][!is.na(domain), ][1:20] %>%
  ggplot(aes(x=reorder(domain, -n), y=n/1000)) +
  geom_bar(stat='identity', fill='steelblue') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(title='Number of visits from top-level domains',
       y='Visits (000s)',
       x='Top-level domain',
       subtitle='Unknown domains excluded')

g2 <- dtrain[!is.na(networkDomain), .(revenue = sum(transactionRevenue, na.rm=TRUE)), by = domain][
  order(-revenue)][
    !is.na(domain), ][1:20] %>%
  ggplot(aes(x=reorder(domain, -revenue), y=revenue/1000)) +
  geom_bar(stat='identity', fill='steelblue') + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(
    title='Revenue from top-level domains', 
    y='Revenue (000s)', 
    x='Top-level domain',
    subtitle='Unknown domains excluded')

grid.arrange(g1, g2)
```


































